### ISSUE TITLE
怎么设置代码高亮?

### ISSUE THREAD

**Issue by caixxiong** [iamcco/markdown-preview.nvim#113]
之前那个vim版本的代码高亮很好看，但是这个版本的代码高亮就不好看了，需要怎么设置么？

**Comment by iamcco** [comment]
下载 https://raw.githubusercontent.com/iamcco/markdown-preview.vim/master/autoload/server/static/styles/highlight/solarized_dark.css

然后设置 `let g:mkdp_highlight_css = 'css 路径'`

**Comment by aytrack** [comment]
我这样设置后一直不生效，版本：`version 8.2.250`

**Comment by iamcco** [comment]
@aytrack 怎么设置的，css 内容是啥

**Comment by aytrack** [comment]
> @aytrack 怎么设置的，css 内容是啥

1. `git clone https://github.com/highlightjs/highlight.js.git` 到 `markdown-preview.nvim`文件夹下
2. `let g:mkdp_highlight_css = '绝对路径/.vim/plugged/markdown-preview.nvim/highlight.js/src/styles/atom-one-dark.css'`

**Comment by iamcco** [comment]
看起来没问题，你说的没生效是只完全没有颜色还是？

**Comment by aytrack** [comment]
不论我修改成哪个主题，都表现为默认的主题

**Comment by iamcco** [comment]
@aytrack 没法复现，你确定这个路径 `绝对路径/.vim/plugged/markdown-preview.nvim/highlight.js/src/styles/atom-one-dark.css`是对的 ?

**Comment by aytrack** [comment]
是的，我直接复制设置的路径通过 vim 打开，内容如下：
```css
/*

Atom One Dark by Daniel Gamage
Original One Dark Syntax theme from https://github.com/atom/one-dark-syntax

base:    #282c34
mono-1:  #abb2bf
mono-2:  #818896
mono-3:  #5c6370
hue-1:   #56b6c2
hue-2:   #61aeee
hue-3:   #c678dd
hue-4:   #98c379
hue-5:   #e06c75
hue-5-2: #be5046
hue-6:   #d19a66
hue-6-2: #e6c07b

*/

.hljs {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
  color: #abb2bf;
  background: #282c34;
}

.hljs-comment,
.hljs-quote {
  color: #5c6370;
  font-style: italic;
}

.hljs-doctag,
.hljs-keyword,
.hljs-formula {
  color: #c678dd;
}

.hljs-section,
.hljs-name,
.hljs-selector-tag,
.hljs-deletion,
.hljs-subst {
  color: #e06c75;
}

.hljs-literal {
  color: #56b6c2;
}

.hljs-string,
.hljs-regexp,
.hljs-addition,
.hljs-attribute,
.hljs-meta-string {
  color: #98c379;
}

.hljs-built_in,
.hljs-class .hljs-title {
  color: #e6c07b;
}

.hljs-attr,
.hljs-variable,
.hljs-template-variable,
.hljs-type,
.hljs-selector-class,
.hljs-selector-attr,
.hljs-selector-pseudo,
.hljs-number {
  color: #d19a66;
}

.hljs-symbol,
.hljs-bullet,
.hljs-link,
.hljs-meta,
.hljs-selector-id,
.hljs-title {
  color: #61aeee;
}

.hljs-emphasis {
  font-style: italic;
}

.hljs-strong {
  font-weight: bold;
}

.hljs-link {
  text-decoration: underline;
}

```
但是实际的高亮显示还是默认的效果
![image](https://user-images.githubusercontent.com/10184437/75255124-67ade680-581c-11ea-9d46-9ed1b6d7d758.png)

浏览器为 chrome：版本 79.0.3945.130（正式版本） （64 位）(在 firefox 上也是一样的效果）
操作系统为：mac os catalina 10.15.2

**Comment by aytrack** [comment]
不好意思，仔细观察了以下，代码的高亮颜色实际上是改变了的，是代码块的背景颜色没有改变

**Comment by iamcco** [comment]
@aytrack 高亮不包括背景色，自己添加 

```css
.markdown-body pre {
  background-color: #000;
}
```
