### ISSUE TITLE
你好,有兩個問題1-能否增加瀏覽器左右寬度?2-為何會有一次回彈動作?

### ISSUE THREAD

**Issue by eternalcyan** [iamcco/markdown-preview.nvim#89]
1. 默認情況下頁面很寬但用到的只有固定的寬度範圍,請問下能把它擴展到全屏嗎?
2. 每次在VIM中定位後,然後焦點切到瀏覽器,滾動之後幾秒鐘後會有一個回彈回VIM光標焦點行的動作,請問能取消這個回彈嗎?我感覺沒啥必要.

非常棒的插件,感謝.

**Comment by iamcco** [comment]
第一个问题，使用 `let g:mkdp_markdown_css = ''` 配置自定义的 css 样式，改写

``` css
#page-ctn {
  margin: 0 auto;
  max-width: 900px;
  color: #24292e;
}
```

第二个问题，`set updatetime=200`  设置下 updatetime 的时间，默认是4秒
